### ISSUE TITLE
Publish remark plugins

### ISSUE THREAD

**Issue by timgreen** [colebemis/lumen#27]
The [remark-plugins](https://github.com/colebemis/lumen/tree/main/src/remark-plugins) you wrote are awesome. And I'd like t o use it in my project (especially `tag-link.ts`).

Do you consider to publish them?

**Comment by colebemis** [comment]
👋 Hi, @timgreen. I don't have plans to publish those plugins separately, mostly because I don't have time to maintain any more open-source projects. Feel free to copy them into your project or publish them yourself!
